version: '3'

tasks:
  default:
    deps: [minidlna, samba]

  minidlna-package:
    cmds:
      - apt-get install minidlna
    status:
      - '[ -f /usr/sbin/minidlnad ]'

  minidlna:
    deps: [minidlna-package]
    cmds:
      - cp ./minidlna/minidlna.conf /etc/minidlna.conf
      - systemctl restart minidlna.service
    sources:
      - ./minidlna/minidlna.conf

  samba:
    cmds:
      - cp ./samba/smb.conf /etc/samba/smb.conf
      - systemctl restart smbd.service
    sources:
      - ./samba/smb.conf
