version: '3'

tasks:
  default:
    deps: [minidlna]

  minidlna:
    cmds:
      - cp ./minidlna/minidlna.conf /etc/minidlna.conf
      - systemctl restart minidlna.service
    sources:
      - ./minidlna/minidlna.conf

  samba:
    cmds:
      - cp ./samba/smb.conf /etc/samba/smb.conf
      - systemctl restart smbd.service
    sources:
      - ./samba/smb.conf
