version: '3'

tasks:
  package:
    cmds:
      - apt-get install minidlna
    status:
      - '[ -f /usr/sbin/minidlnad ]'

  configure:
    deps: [package]
    cmds:
      - cp ./minidlna.conf /etc/minidlna.conf
      - systemctl restart minidlna.service
    sources:
      - ./minidlna.conf
