version: '3'

tasks:
  package:
    cmds:
      - apt-get install minidlna
    status:
      - '[ -f /usr/sbin/minidlnad ]'

  configure:
    deps: [package]
    cmds:
      - cp '{{.TASKFILE_DIR}}/minidlna.conf' /etc/minidlna.conf
      - systemctl restart minidlna.service
    sources:
      - '{{.TASKFILE_DIR}}/minidlna.conf'
